language: php

php:
  - 8.3
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist

script:
  - bin/php-cs-fixer fix --config=".php-cs-fixer.dist.php"
  - bin/phpstan analyse --configuration=".phpstan.neon" --level=8
  - bin/phpunit tests --colors